import React from "react"
import KeyboardButton from "./KeyboardButton.js"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  KeyboardButton,
  "https://www.figma.com/design/IblwUkuftOLr6BEjHK3uqF/%F0%9F%94%B5--MCP?node-id=7039%3A1334",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "slotIcon": figma.instance('-> slot <Icon>'),
      // "label": figma.string('label'),
      // "state": figma.enum('state', {
      //   "pressed": "pressed",
      //   "default": "default"
      // }),
      // "isAction": figma.boolean('isAction')
    },
    example: (props) => (
      <KeyboardButton label={/* TODO */} onPress={/* TODO */} />
    ),
  },
)
