import React from "react";
import KeyboardButton from "../components/KeyboardButton.js";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * Updated to align with the style of components/controls/button.tsx
 */

interface KeyboardButtonProps {
  slotIcon?: React.ReactNode | null;
  label?: string;
  state?: "pressed" | "default";
  labelType?: "symbol" | "icon";
}

figma.connect(
  KeyboardButton,
  "https://www.figma.com/design/IblwUkuftOLr6BEjHK3uqF/%F0%9F%94%B5--MCP?node-id=7039%3A1334",
  {
    props: {
      slotIcon: figma.instance("-> slot <Icon>"), // Use instance for icon
      label: figma.string("label"), // Use string for label
      state: figma.enum("state", {
        pressed: "pressed",
        default: "default",
      }),
      isAction: figma.boolean("isAction"), // Boolean to determine action
    },
    example: (props) => {
      // Determine the label based on isAction
      const label = props.isAction ? props.slotIcon : props.label;

      return (
        <KeyboardButton 
          onPress={() => console.log("Button pressed")}
          label={label}
        />
      );
    },
  },
);