import React from "react"
import KeyboardButton from "../components/KeyboardButton.js"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  KeyboardButton,
  "https://www.figma.com/design/IblwUkuftOLr6BEjHK3uqF/%F0%9F%94%B5--MCP?node-id=7039%3A1334",
  {
    props: {
      slotIcon: figma.instance("-> slot <Icon>"),
      label: figma.string("label"),
      state: figma.enum("state", {
        pressed: "pressed",
        default: "default",
      }),
      labeltype: figma.enum("label-type", {
        symbol: "symbol",
        icon: "icon",
      }),
    },
    example: (props) => (
      <KeyboardButton 
        onPress={() => {}}
        labelType={props.labeltype}
        icon={props.slotIcon}
      >
        {props.label}
      </KeyboardButton>
    ),
  },
)
